package gsoc
package contributors

import cats.data.NonEmptyList

// the order matters! Check step 5 of the README for details.
val allContributors = NonEmptyList.of(
  arnvptl,
  gfinol,
  hehelego,
  synan_mannan,
  `manoj-apj`,
  antoniojimeneznieto,
  `tanmay_008`,
  abh80,
  jnnfrpyn,
  `typelevel-bot`,
  `im-vedant`,
  jmesyou,
  `Arunanshu655`,
  abby_ql,
  justaanand50,
  codebydeepankar,
  parthmozarkar,
  `scala-steward`,
  `the-ivii`,
  `Anurag300705`,
  `piyush-t24`,
  malladinagarjuna2,
  ankitkumarrain,
  valencik,
  `zayd-r`,
  loladenney,
  armanbilge,
  guptapratykshh,
  ap44444,
  saifk16,
  `alokkumardalei-wq`,
  `nvshinde`,
  lucasdu2,
  boss6825,
  yummy_yums,
  `thonkpad`,
  kierinbell,
  jarmuszz,
  blagogunev,
  `octocat`,
  djspiewak,
  `krrishverma1805-web`
)
